POST http://localhost:4000
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation itemData($id : String!, $name : String!, $weight: String!){
  addWeight(id : $id, name : $name, weight:$weight) 
}

{
    "id" : "1",
    "name" : "temp",
    "weight" : "20"
}