POST http://localhost:4000
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation itemData($id : String!, $name : String!, $fire: String!){
  addFire(id : $id, name : $name, fire:$fire) 
}

{
    "id" : "1",
    "name" : "fire",
    "fire" : "1"
}