POST http://localhost:4000
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation itemData($id : Int!, $weight : Int!){
  addItem(id : $id, weight : $weight) 
}

{
    "id" : 5,
    "weight" : 8
}